### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by Code0x58** [gulyasm/jsonui#6]
It would be nice for non-Goers to be able to get binary releases, you could do something like mentioned in [this PR](https://github.com/atombender/ktail/pull/2).

**Comment by gulyasm** [comment]
I will put this on my next feature-to-develop. I'm on vacation this month, but I will try to land it as soon as possible.

Thanks for the suggestion!

**Comment by gulyasm** [comment]
@Code0x58 I added releases and also a wiki page based on the wuzz project.
Sorry for the late response, I was a bit buried.
